// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExternalImportTriggerController from "./external_import_trigger_controller"
application.register("external-import-trigger", ExternalImportTriggerController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import ResultsImportTriggerController from "./results_import_trigger_controller"
application.register("results-import-trigger", ResultsImportTriggerController)

import TableFiltersController from "./table_filters_controller"
application.register("table-filters", TableFiltersController)
