default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= Rails.application.credentials.db.name %>
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>

development:
  <<: *default

test:
  <<: *default
  database: <%= Rails.application.credentials.db.name %><%= ENV['TEST_ENV_NUMBER'] %>

staging:
  <<: *default

production:
  <<: *default